pipeline {
  agent {
    dockerfile {
      dir 'automation'
      reuseNode true
      args '--network host'
    }
  }

  stages {
    stage('Rust Toolchain Info') {
      steps {
        sh 'rustc --version'
      }
    }
    stage('Clippy') {
      steps {
        sh 'cargo clippy'
      }
    }
    stage('Docs') {
      steps {
        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
          sh 'cargo +nightly doc --all-features'
        }
      }
    }
    stage('Rustfmt') {
      steps {
        sh 'cargo fmt --all --check'
      }
    }
    stage('Test') {
      steps {
        sh 'cargo test --all-features'
      }
    }
    stage('Check with all features') {
      steps {
        sh 'cargo check --all-features'
      }
    }
    stage('Check with no features') {
      steps {
        sh 'cargo check --no-default-features'
      }
    }
    stage('Check Cross Embedded Bare Metal') {
      steps {
        sh 'cargo check -p satrs-core --target thumbv7em-none-eabihf --no-default-features'
      }
    }
    stage('Check Cross Embedded Linux') {
      steps {
        sh 'cargo check --target armv7-unknown-linux-gnueabihf'
      }
    }
    stage('Deploy satrs-book') {
      when {
        branch 'main'
      }
      steps {
        dir('satrs-book') {
          mdbook build
          sshagent(credentials: ['documentation-buildfix']) {
            // Deploy to Apache webserver
            sh 'rsync -r --delete book/ buildfix@documentation.irs.uni-stuttgart.de:/projects/sat-rs'
          }
        }
      }
    }
  }
}
